name: CI

on:
  push:
    branches:
      - main  # Run CI on pushes to the main branch
  pull_request:
    branches:
      - main  # Run CI on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Step 3.1: Install pre-commit hooks
      - name: run pre-commit hooks
        run: |
          pre-commit run --all-files

      # Step 4: Run unit tests
      - name: Run Unit Tests
        run: python -m unittest discover -s human_readable_cron/test -p "*.py"

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: sumanengg/human-readble-cron

      # Step 4: Run tests with coverage
      - name: Run tests with coverage
        run: |
            coverage run -m unittest discover -s human_readable_cron/test -p "*.py"
            coverage xml

     # Step 5: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            files: coverage.xml
            flags: unittests
            name: codecov-coverage
